### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by comtechnik** [greenMikeEU/SmartMeterEVNKaifaMA309#3]
Hallo Michael,
habe alle Pakete ohne Fehlermeldung installier.
Nach langem Warten heute Endlich mein Adapter gekommen, 
deine EvnSmartmeterMQTTKaifaMA309.py mit dem EVN Schlüssel und COM-Port angepasst und Pfad angepasst.
Mqtt habe ich deaktiviert, bekomme beim starten der Datei bekomme ich immer diese Fehlermeldung:

Traceback (most recent call last):
  File "/home/pi/Desktop/EvnSmartmeterMQTTKaifaMA309.py", line 2, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

Kannst du mir bitte helfen? DANKE!

**Comment by greenMikeEU** [comment]
Hallo,

das musst du noch installieren

sudo pip3 install pyserial. 

Bei weiteren Fragen oder Fehlermeldung kannst du mir gerne eine Mail schreiben dann kann ich dir meine Nummer geben dann können wir schnell eine Lösung finden.
mreitbauer@gmx.net
LG Michael

**Comment by comtechnik** [comment]
Danke hab dir Nummer geschickt!

**Comment by comtechnik** [comment]
Neue Fehlermeldung:


pi@smartmeter:~ $ sudo python3 /home/pi/Desktop/EvnSmartmeterMQTTKaifaMA309.py
68fafa6853ff000167db084b464d10200195028201552100042065ed68081e1bf43048a0a777447d                                                                         78e473a45baf36915573a1f5f2c43cb603c04aa889c5eb3dcd28ab1ab9e411e07966e3cf2c96a701                                                                         8e2f4d97d651f26f6e8cfc793721548c125b051a73c0a4a69f6c56c8c143791b29087a5ab43883a6                                                                         87afac691ba7570a2e1ea790886e5448fb223208172fc17508d4886ec46b78a559d28a044dd1b00b                                                                         300a13b356ddea616e0e2393870737a107cdd2b80c67fa74801f575e45827b183c838184f42477f1                                                                         f130971952301df43313e70dc76fd8ce1b6b8979d521cf3107ad11fbd952f7219cb114c07dcd9426                                                                         8408a8f9269292d5c6480bdfd7dd17166872726853ff1101676a83a4636817aea011c0d5ae9c9c30                                                                         ccbd
Traceback (most recent call last):
  File "/home/pi/Desktop/EvnSmartmeterMQTTKaifaMA309.py", line 65, in <module>
    soup = BeautifulSoup(xml, 'lxml')
  File "/usr/local/lib/python3.9/dist-packages/bs4/__init__.py", line 248, in __                                                                         init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requeste                                                                         d: lxml. Do you need to install a parser library?

**Comment by greenMikeEU** [comment]
Hallo,
leider gibt es manchmal ein Problem mit der lxml die kann nicht richtig installiert werden am besten du Versuchst einmal
auf das umzubessern.
`soup = BeautifulSoup(xml, ‘html.parser’)`

**Comment by comtechnik** [comment]
funktioniert leider auch nicht :-( schade

*Fehlermeldung:*


***@***.***:~ $ sudo python3
/home/pi/Desktop/EvnSmartmeterMQTTKaifaMA309.py
  File "/home/pi/Desktop/EvnSmartmeterMQTTKaifaMA309.py", line 65
    soup = BeautifulSoup(xml, ‘html.parser’)
                              ^
SyntaxError: invalid character '‘' (U+2018)
***@***.***:~ $


Am Do., 2. Juni 2022 um 10:07 Uhr schrieb greenMike <
***@***.***>:

**Comment by fuzi1986** [comment]
@comtechnik 
Das Zeichen vor html. ist das falsch, würde zumindest die Fehlermeldung aus sagen.
richtig müsste es so sein _soup = BeautifulSoup(xml, 'html.parser’)_

**Comment by greenMikeEU** [comment]
Hallo,
danke für die Info ich werde es die nächsten Tage erweitern.
